name: Coverity Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      languages:
        description: "Languages to analyze"
        required: true
        default: "c-cpp"
jobs:
  coverity:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          # Update package lists and install required libraries for building and linking
          sudo apt update
          sudo apt install -y build-essential libcurl4-openssl-dev libssl-dev libmongoc-dev

      - name: Download and Install Coverity Tool
        run: |
          # Download and extract the Coverity analysis tool
          wget https://scan.coverity.com/download/linux64 \
            --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=${{ github.repository }}" \
            -O coverity_tool.tgz
          mkdir coverity_tool
          tar -xvzf coverity_tool.tgz -C coverity_tool --strip-components=1
          export PATH=$PWD/coverity_tool/bin:$PATH
          echo "Coverity Tool installed successfully"

      - name: Build with Coverity (compile each TU separately)
        run: |
          set -o pipefail
          echo "Compiling project (Coverity capture)"
          mkdir -p build

          # Counters
          FAILURES=0
          TOTAL=0

          # Find all .cpp files (handles spaces/newlines)
          find . -type f -name "*.cpp" -print0 | while IFS= read -r -d '' file; do
            # Skip coverity intermediate dir, .git, build, and coverity tooling itself
            case "$file" in
              ./cov-int/*|./.git/*|./coverity_tool/*|./build/*) continue ;;
            esac

            # Optionally skip platform-specific Windows files that include windows.h
            if grep -Iq "windows.h" "$file"; then
              echo "Skipping Windows-only file: $file"
              continue
            fi

            TOTAL=$((TOTAL+1))
            echo "Compiling TU ($TOTAL): $file"

            # Run cov-build for a single translation unit (compile only)
            # If compile fails, record but continue — we'll check coverage later.
            coverity_tool/bin/cov-build --dir cov-int g++ -c "$file" -o "build/$(basename "$file" .cpp).o" -Wall -O2 -std=c++17 -fPIC -I. -lcurl -lssl -lmongoc-1.0 || {
              echo ">> Compile failed for: $file"
              FAILURES=$((FAILURES+1))
            }
          done

          echo "Total TU candidates found: ${TOTAL}, failures: ${FAILURES}"


          if ls build/*.o >/dev/null 2>&1; then
            echo "Attempting to link objects into a test binary (ignored failures)..."
            g++ build/*.o -o build/yrpreyc -lcurl -lssl -lmongoc-1.0 || true
          fi

          echo "Capture summary (last lines of cov-int/build-log.txt):"
          tail -n 60 cov-int/build-log.txt || true





      - name: Compress with bzip2
        run: |
          # Compress the Coverity intermediate directory for upload
          tar cjvf myproject.tar.bz2 cov-int
        id: compress

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "coverity-scan-${{ github.run_id }}"
          release_name: "Coverity Scan Results"
          body: "Automated Coverity Scan Results"
          draft: false
          prerelease: false

      - name: Upload Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: myproject.tar.bz2
          asset_name: myproject.tar.bz2
          asset_content_type: application/x-bzip2

      - name: Notify Coverity Scan
        run: |
          # Notify Coverity Scan service with the results
          curl --data "project=${{ github.repository }}&token=${{ secrets.COVERITY_TOKEN }}&email=cpp.benchmark@proton.me&url=https://github.com/${{ github.repository }}/releases/download/coverity-scan-${{ github.run_id }}/myproject.tar.bz2&version=1.0&description=Automated+Coverity+Scan" https://scan.coverity.com/builds