name: Coverity Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      languages:
        description: "Languages to analyze"
        required: true
        default: "c-cpp"
jobs:
  coverity:
    runs-on: windows-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        shell: pwsh
        run: |
          choco install msys2 -y
          $env:Path += ";C:\msys64\usr\bin"
          pacman -Syu --noconfirm
          pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-curl mingw-w64-x86_64-openssl mingw-w64-x86_64-mongo-c-driver
          $env:Path += ";C:\msys64\mingw64\bin"

      - name: Download and Install Coverity Tool
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://scan.coverity.com/download/win64" -Method Post -Body "token=${{ secrets.COVERITY_TOKEN }}&project=${{ github.repository }}" -OutFile "coverity_tool.zip"
          New-Item -ItemType Directory -Path "coverity_tool" -Force | Out-Null
          Expand-Archive -Force coverity_tool.zip -DestinationPath "coverity_tool"
          $Env:PATH = "$PWD\coverity_tool\bin;$Env:PATH"
          Write-Output "Coverity Tool installed successfully"

      - name: Build with Coverity
        shell: pwsh
        run: |
          $covBuildPath = Get-ChildItem -Path "coverity_tool" -Recurse -Filter "cov-build.exe" | Select-Object -First 1 -ExpandProperty FullName
          if (-not $covBuildPath) {
            Write-Error "Coverity build tool not found"
            exit 1
          }
          Get-ChildItem -Directory | ForEach-Object {
            $CppFile = Get-ChildItem -Path $_.FullName -Filter *.cpp | Select-Object -First 1
            if ($CppFile) {
              Write-Output "Building $($CppFile.FullName)"
              & $covBuildPath --dir "cov-int" g++ -I"C:\msys64\mingw64\include" -I"C:\msys64\mingw64\include\libmongoc-1.0" -I"C:\msys64\mingw64\include\curl" $CppFile.FullName -o "$($_.Name).exe" -L"C:\msys64\mingw64\lib" -lmongoc-1.0 -lcurl -lssl -lcrypto -lws2_32
            }
          }

      - name: Compress with bzip2
        run: |
          Compress-Archive -Path cov-int -DestinationPath myproject.zip
        id: compress

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "coverity-scan-${{ github.run_id }}"
          release_name: "Coverity Scan Results"
          body: "Automated Coverity Scan Results"
          draft: false
          prerelease: false

      - name: Upload Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: myproject.zip
          asset_name: myproject.zip
          asset_content_type: application/x-bzip2

      - name: Notify Coverity Scan
        run: |
          Invoke-WebRequest -Uri "https://scan.coverity.com/builds" -Method Post -Body @{
            project     = "${{ github.repository }}"
            token       = "${{ secrets.COVERITY_TOKEN }}"
            email       = "cpp.benchmark@proton.me"
            url         = "https://github.com/${{ github.repository }}/releases/download/coverity-scan-${{ github.run_id }}/myproject.zip"
            version     = "1.0"
            description = "Automated Coverity Scan"
          }